version: "3"
services:
    db:
        container_name: mydb
        image: mysql:5.7
        ports:
            - "32001:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
    app:
        container_name: clvwebapp
        links:
            - "db"
        build: ./
        ports:
            - "8501:8501"